help:
  - "yea"
  - "yea"
  - "yea"
  - "yea"
  - "yea"
spawn:
  x: 63
  y: 38
  z: 260
# %line% - Line
# %player% - Player Name
# %doublearrow% - »
join:
  - "yea"
  - "%line%"
  - "%player%"
  - "%doublearrow%"
  - "yea"
discord: "yea"
telegram: "yea"
teamspeak: "yea"
