name: Coruscant
version: 1.0-SNAPSHOT
main: dev.brew.Coruscant
commands:
  gmc:
  gms:
  help:
  discord:
    aliases: [dc, disc]
  telegram:
    aliases: [tele]
  teamspeak:
    aliases: [ts]
  speed:
    aliases: [sp, fastasfuckboy]
  invis:
    aliases: [inv, invisiblity]
  fire:
    aliases: [fr, fireres]
  alert:
  craft:
    aliases: [craftingtable, crafting, workbench]
  tp:
    aliases: [teleport]
  tphere:
    aliases: [s, bring, drag]
  tppos:
    aliases:  [tppossiton, tpcords]
