name: Coruscant
version: 1.0-SNAPSHOT
main: dev.brew.Coruscant
commands:
  gmc:
  gms:
  help:
  discord:
    aliases: [dc, disc]
  telegram:
    aliases: [tele]
  teamspeak:
    aliases: [ts]
  speed:
    aliases: [sp, fastasfuckboy]
  invis:
    aliases: [inv, invisiblity]
  fire:
    aliases: [fr, fireres]
  alert:
  heal:
  clearinventory:
    aliases: [ci, niggaremovemyinventory]
  copyinventory:
    aliases: [cpinv, cpfrom]
  fly:
  eat:
    aliases: [feed]
  craft:
    aliases: [craftingtable, crafting, workbench]
  teleport:
    aliases: [tp]
  tphere:
    aliases: [s, bring, drag]
  tppos:
    aliases:  [tppossiton, tpcords]
